#!/bin/bash
echo 'input file name'
read filename
echo '#include <stdio.h>
/**
* main - Entry point
*
* Description: A C program that prints with put function
*
* Return: Alawys 0 (Success)
*/
     int main(void)' > ${filename}
#echo 'wrait the code'
#read code
echo '{' >> ${filename}
#echo '	'${code} >> ${filename}

echo '}' >> ${filename}
vi ${filename}
betty ${filename}
git add . && git commit -m "upload script files at my dic" && git push
#echo 'enter your commit to up to githup'
#read commit
#git add . 
#git commit -m ${commit}
#git push
#clear
